### ISSUE TITLE
fetch(key) issue

### ISSUE THREAD

**Issue by KristenPeckBC** [poissonconsulting/nrp#1]
> ?nrp
Error in fetch(key) : 
  lazy-load database 'C:/Users/Kristen/R/win-library/3.5/nrp/help/nrp.rdb' is corrupt

Any ideas? I downloaded nrp-0.1.0.tar.gz directly from your github release.

**Comment by joethorley** [comment]
Try installing using 

```
if(!"drat" %in% installed.packages()[,1]) 
  install.packages("drat")
drat::addRepo("poissonconsulting")
devtools::install_github("poissonconsulting/nrp")
```

**Comment by KristenPeckBC** [comment]
Hi Joe- on work computer with R 3.6.0 newly installed, this is what I get back:

> devtools::install_github("poissonconsulting/nrp")
Downloading GitHub repo poissonconsulting/nrp@master
Downloading GitHub repo poissonconsulting/dttr2@master
Downloading GitHub repo tidyverse/hms@master
Installing 3 packages: pkgconfig, vctrs, zeallot
Installing packages into ‘C:/Users/krispeck/R/win-library/3.6’
(as ‘lib’ is unspecified)
Error: (converted from warning) unable to access index for repository https://poissonconsulting.github.io/drat/bin/windows/contrib/3.6:
  cannot open URL 'https://poissonconsulting.github.io/drat/bin/windows/contrib/3.6/PACKAGES'

Have you updated drat to 3.6?

Even with 3.5.3, I had trouble installing the nrp package with devtools::install_github("poissonconsulting/nrp") because I need to manually download many of the dependencies on my work computer and a few on my home computer too (e.g. pkgbuild, backport). Not sure how to fix this so it works more automatically, it might be a more general gov't computer issue?

**Comment by joethorley** [comment]
Hi @KristenPeckBC 

Can you try the following
```
if(!"drat" %in% installed.packages()[,1]) 
  install.packages("drat")
drat::addRepo("poissonconsulting")
install.packages("nrp")
```

**Comment by KristenPeckBC** [comment]
Yes, that worked on my gov computer! My original issue (fetch(key)) is also resolved. I'll get a few others to test as well. Thanks!

**Comment by joethorley** [comment]
That's great - I've also updated the README to indicate how to install.
