### ISSUE TITLE
GitHub Actions - failing 

### ISSUE THREAD

**Issue by aylapear** [poissonconsulting/nrp#4]
Both coverage and R-CMD-checks failing due to a dependency issue.

**Comment by joethorley** [comment]
also pkgdown. 

It seems to be due to the cache being messed up as the same scripts work on other packages.

![Uploading Screen Shot 2020-11-03 at 18.06.57.png…]()

**Comment by joethorley** [comment]
Fixed by setting 
```
          install.packages('remotes',  repos = "http://cran.rstudio.com/")
```

**Comment by joethorley** [comment]
weirdly removing remotes breaks them - see issue #5
